# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test_and_development

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#    - uses: actions/download-artifact@v3
#      with:
#        name: Download signed.json
    - name: Move Model and Start jksb Direct
#      if: always()
      env:
        mail_id: ${{secrets.mail_id}}
        mail_pd: ${{secrets.mail_pd}}
        processing_pool: ${{secrets.test_processing_pool}}
      run: |
        mkdir ~/.cnocr
        mkdir ~/.cnocr/2.2
        mkdir ~/.cnocr/2.2/densenet_lite_136-fc 
        mkdir ~/.cnocr/1.2
        mkdir ~/.cnocr/1.2/ppocr/
        mv ./models/ch_PP-OCRv3_rec_infer.onnx ~/.cnocr/1.2/ppocr
        mv ./models/cnocr-v2.2-densenet_lite_136-fc-epoch=039-complete_match_epoch=0.8597-model.onnx ~/.cnocr/2.2/densenet_lite_136-fc
        python Application.py "$mail_id" "$mail_pd" "$processing_pool"
#    - uses: actions/upload-artifact@v3
#      if: always()
#      with:
#        name: Upload signed.json
#        path: signed.json
